name: kinite_engine
description: Fully optimized TTS with Kokoro, Kitten, Piper, Coqui
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sherpa_onnx: ^1.12.28
  device_info_plus: ^10.1.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  url_launcher: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/rex_core/espeak-ng-data/
    - assets/icon.png
    - assets/rex_core/tokens.txt
    - assets/rex_engines/kokoro/model.ort
    - assets/rex_engines/kokoro/voices.bin
    - assets/rex_engines/kokoro/tokens.txt
    - assets/rex_engines/kokoro/speakers.json
    - assets/rex_engines/kitten/model.ort
    - assets/rex_engines/kitten/voices.bin
    - assets/rex_engines/kitten/tokens.txt
    - assets/rex_engines/piper/model.ort
    - assets/rex_engines/piper/amy.json
    - assets/rex_engines/piper/tokens.txt
    - assets/rex_engines/coqui/model.ort
    - assets/rex_engines/coqui/vctk.json
    - assets/rex_engines/coqui/tokens.txt
    - assets/rex_core/espeak-ng-data/af_dict
    - assets/rex_core/espeak-ng-data/am_dict
    - assets/rex_core/espeak-ng-data/an_dict
    - assets/rex_core/espeak-ng-data/ar_dict
    - assets/rex_core/espeak-ng-data/as_dict
    - assets/rex_core/espeak-ng-data/az_dict
    - assets/rex_core/espeak-ng-data/ba_dict
    - assets/rex_core/espeak-ng-data/be_dict
    - assets/rex_core/espeak-ng-data/bg_dict
    - assets/rex_core/espeak-ng-data/bn_dict
    - assets/rex_core/espeak-ng-data/bpy_dict
    - assets/rex_core/espeak-ng-data/bs_dict
    - assets/rex_core/espeak-ng-data/ca_dict
    - assets/rex_core/espeak-ng-data/chr_dict
    - assets/rex_core/espeak-ng-data/cmn_dict
    - assets/rex_core/espeak-ng-data/cs_dict
    - assets/rex_core/espeak-ng-data/cv_dict
    - assets/rex_core/espeak-ng-data/cy_dict
    - assets/rex_core/espeak-ng-data/da_dict
    - assets/rex_core/espeak-ng-data/de_dict
    - assets/rex_core/espeak-ng-data/el_dict
    - assets/rex_core/espeak-ng-data/en_dict
    - assets/rex_core/espeak-ng-data/eo_dict
    - assets/rex_core/espeak-ng-data/es_dict
    - assets/rex_core/espeak-ng-data/et_dict
    - assets/rex_core/espeak-ng-data/eu_dict
    - assets/rex_core/espeak-ng-data/fa_dict
    - assets/rex_core/espeak-ng-data/fi_dict
    - assets/rex_core/espeak-ng-data/fr_dict
    - assets/rex_core/espeak-ng-data/ga_dict
    - assets/rex_core/espeak-ng-data/gd_dict
    - assets/rex_core/espeak-ng-data/gn_dict
    - assets/rex_core/espeak-ng-data/grc_dict
    - assets/rex_core/espeak-ng-data/gu_dict
    - assets/rex_core/espeak-ng-data/hak_dict
    - assets/rex_core/espeak-ng-data/haw_dict
    - assets/rex_core/espeak-ng-data/he_dict
    - assets/rex_core/espeak-ng-data/hi_dict
    - assets/rex_core/espeak-ng-data/hr_dict
    - assets/rex_core/espeak-ng-data/ht_dict
    - assets/rex_core/espeak-ng-data/hu_dict
    - assets/rex_core/espeak-ng-data/hy_dict
    - assets/rex_core/espeak-ng-data/ia_dict
    - assets/rex_core/espeak-ng-data/id_dict
    - assets/rex_core/espeak-ng-data/intonations
    - assets/rex_core/espeak-ng-data/io_dict
    - assets/rex_core/espeak-ng-data/is_dict
    - assets/rex_core/espeak-ng-data/it_dict
    - assets/rex_core/espeak-ng-data/ja_dict
    - assets/rex_core/espeak-ng-data/jbo_dict
    - assets/rex_core/espeak-ng-data/ka_dict
    - assets/rex_core/espeak-ng-data/kk_dict
    - assets/rex_core/espeak-ng-data/kl_dict
    - assets/rex_core/espeak-ng-data/kn_dict
    - assets/rex_core/espeak-ng-data/ko_dict
    - assets/rex_core/espeak-ng-data/kok_dict
    - assets/rex_core/espeak-ng-data/ku_dict
    - assets/rex_core/espeak-ng-data/ky_dict
    - assets/rex_core/espeak-ng-data/la_dict
    - assets/rex_core/espeak-ng-data/lb_dict
    - assets/rex_core/espeak-ng-data/lfn_dict
    - assets/rex_core/espeak-ng-data/lt_dict
    - assets/rex_core/espeak-ng-data/lv_dict
    - assets/rex_core/espeak-ng-data/manifest.txt
    - assets/rex_core/espeak-ng-data/mi_dict
    - assets/rex_core/espeak-ng-data/mk_dict
    - assets/rex_core/espeak-ng-data/ml_dict
    - assets/rex_core/espeak-ng-data/mr_dict
    - assets/rex_core/espeak-ng-data/ms_dict
    - assets/rex_core/espeak-ng-data/mt_dict
    - assets/rex_core/espeak-ng-data/mto_dict
    - assets/rex_core/espeak-ng-data/my_dict
    - assets/rex_core/espeak-ng-data/nci_dict
    - assets/rex_core/espeak-ng-data/ne_dict
    - assets/rex_core/espeak-ng-data/nl_dict
    - assets/rex_core/espeak-ng-data/no_dict
    - assets/rex_core/espeak-ng-data/nog_dict
    - assets/rex_core/espeak-ng-data/om_dict
    - assets/rex_core/espeak-ng-data/or_dict
    - assets/rex_core/espeak-ng-data/pa_dict
    - assets/rex_core/espeak-ng-data/pap_dict
    - assets/rex_core/espeak-ng-data/phondata
    - assets/rex_core/espeak-ng-data/phondata-manifest
    - assets/rex_core/espeak-ng-data/phonindex
    - assets/rex_core/espeak-ng-data/phontab
    - assets/rex_core/espeak-ng-data/piqd_dict
    - assets/rex_core/espeak-ng-data/pl_dict
    - assets/rex_core/espeak-ng-data/pt_dict
    - assets/rex_core/espeak-ng-data/py_dict
    - assets/rex_core/espeak-ng-data/qdb_dict
    - assets/rex_core/espeak-ng-data/qu_dict
    - assets/rex_core/espeak-ng-data/quc_dict
    - assets/rex_core/espeak-ng-data/qya_dict
    - assets/rex_core/espeak-ng-data/ro_dict
    - assets/rex_core/espeak-ng-data/ru_dict
    - assets/rex_core/espeak-ng-data/sd_dict
    - assets/rex_core/espeak-ng-data/shn_dict
    - assets/rex_core/espeak-ng-data/si_dict
    - assets/rex_core/espeak-ng-data/sjn_dict
    - assets/rex_core/espeak-ng-data/sk_dict
    - assets/rex_core/espeak-ng-data/sl_dict
    - assets/rex_core/espeak-ng-data/smj_dict
    - assets/rex_core/espeak-ng-data/sq_dict
    - assets/rex_core/espeak-ng-data/sr_dict
    - assets/rex_core/espeak-ng-data/sv_dict
    - assets/rex_core/espeak-ng-data/sw_dict
    - assets/rex_core/espeak-ng-data/ta_dict
    - assets/rex_core/espeak-ng-data/te_dict
    - assets/rex_core/espeak-ng-data/th_dict
    - assets/rex_core/espeak-ng-data/tk_dict
    - assets/rex_core/espeak-ng-data/tn_dict
    - assets/rex_core/espeak-ng-data/tr_dict
    - assets/rex_core/espeak-ng-data/tt_dict
    - assets/rex_core/espeak-ng-data/ug_dict
    - assets/rex_core/espeak-ng-data/uk_dict
    - assets/rex_core/espeak-ng-data/ur_dict
    - assets/rex_core/espeak-ng-data/uz_dict
    - assets/rex_core/espeak-ng-data/vi_dict
    - assets/rex_core/espeak-ng-data/yue_dict
    - assets/rex_core/espeak-ng-data/lang/eu
    - assets/rex_core/espeak-ng-data/lang/ko
    - assets/rex_core/espeak-ng-data/lang/qu
    - assets/rex_core/espeak-ng-data/lang/aav/vi
    - assets/rex_core/espeak-ng-data/lang/aav/vi-VN-x-central
    - assets/rex_core/espeak-ng-data/lang/aav/vi-VN-x-south
    - assets/rex_core/espeak-ng-data/lang/art/eo
    - assets/rex_core/espeak-ng-data/lang/art/ia
    - assets/rex_core/espeak-ng-data/lang/art/io
    - assets/rex_core/espeak-ng-data/lang/art/jbo
    - assets/rex_core/espeak-ng-data/lang/art/lfn
    - assets/rex_core/espeak-ng-data/lang/art/piqd
    - assets/rex_core/espeak-ng-data/lang/art/py
    - assets/rex_core/espeak-ng-data/lang/art/qdb
    - assets/rex_core/espeak-ng-data/lang/art/qya
    - assets/rex_core/espeak-ng-data/lang/art/sjn
    - assets/rex_core/espeak-ng-data/lang/azc/nci
    - assets/rex_core/espeak-ng-data/lang/bat/lt
    - assets/rex_core/espeak-ng-data/lang/bat/ltg
    - assets/rex_core/espeak-ng-data/lang/bat/lv
    - assets/rex_core/espeak-ng-data/lang/bnt/sw
    - assets/rex_core/espeak-ng-data/lang/bnt/tn
    - assets/rex_core/espeak-ng-data/lang/ccs/ka
    - assets/rex_core/espeak-ng-data/lang/cel/cy
    - assets/rex_core/espeak-ng-data/lang/cel/ga
    - assets/rex_core/espeak-ng-data/lang/cel/gd
    - assets/rex_core/espeak-ng-data/lang/cus/om
    - assets/rex_core/espeak-ng-data/lang/dra/kn
    - assets/rex_core/espeak-ng-data/lang/dra/ml
    - assets/rex_core/espeak-ng-data/lang/dra/ta
    - assets/rex_core/espeak-ng-data/lang/dra/te
    - assets/rex_core/espeak-ng-data/lang/esx/kl
    - assets/rex_core/espeak-ng-data/lang/gmq/da
    - assets/rex_core/espeak-ng-data/lang/gmq/is
    - assets/rex_core/espeak-ng-data/lang/gmq/nb
    - assets/rex_core/espeak-ng-data/lang/gmq/sv
    - assets/rex_core/espeak-ng-data/lang/gmw/af
    - assets/rex_core/espeak-ng-data/lang/gmw/de
    - assets/rex_core/espeak-ng-data/lang/gmw/en
    - assets/rex_core/espeak-ng-data/lang/gmw/en-029
    - assets/rex_core/espeak-ng-data/lang/gmw/en-GB-scotland
    - assets/rex_core/espeak-ng-data/lang/gmw/en-GB-x-gbclan
    - assets/rex_core/espeak-ng-data/lang/gmw/en-GB-x-gbcwmd
    - assets/rex_core/espeak-ng-data/lang/gmw/en-GB-x-rp
    - assets/rex_core/espeak-ng-data/lang/gmw/en-US
    - assets/rex_core/espeak-ng-data/lang/gmw/en-US-nyc
    - assets/rex_core/espeak-ng-data/lang/gmw/lb
    - assets/rex_core/espeak-ng-data/lang/gmw/nl
    - assets/rex_core/espeak-ng-data/lang/grk/el
    - assets/rex_core/espeak-ng-data/lang/grk/grc
    - assets/rex_core/espeak-ng-data/lang/inc/as
    - assets/rex_core/espeak-ng-data/lang/inc/bn
    - assets/rex_core/espeak-ng-data/lang/inc/bpy
    - assets/rex_core/espeak-ng-data/lang/inc/gu
    - assets/rex_core/espeak-ng-data/lang/inc/hi
    - assets/rex_core/espeak-ng-data/lang/inc/kok
    - assets/rex_core/espeak-ng-data/lang/inc/mr
    - assets/rex_core/espeak-ng-data/lang/inc/ne
    - assets/rex_core/espeak-ng-data/lang/inc/or
    - assets/rex_core/espeak-ng-data/lang/inc/pa
    - assets/rex_core/espeak-ng-data/lang/inc/sd
    - assets/rex_core/espeak-ng-data/lang/inc/si
    - assets/rex_core/espeak-ng-data/lang/inc/ur
    - assets/rex_core/espeak-ng-data/lang/ine/hy
    - assets/rex_core/espeak-ng-data/lang/ine/hyw
    - assets/rex_core/espeak-ng-data/lang/ine/sq
    - assets/rex_core/espeak-ng-data/lang/ira/fa
    - assets/rex_core/espeak-ng-data/lang/ira/fa-Latn
    - assets/rex_core/espeak-ng-data/lang/ira/ku
    - assets/rex_core/espeak-ng-data/lang/iro/chr
    - assets/rex_core/espeak-ng-data/lang/itc/la
    - assets/rex_core/espeak-ng-data/lang/jpx/ja
    - assets/rex_core/espeak-ng-data/lang/map/haw
    - assets/rex_core/espeak-ng-data/lang/miz/mto
    - assets/rex_core/espeak-ng-data/lang/myn/quc
    - assets/rex_core/espeak-ng-data/lang/poz/id
    - assets/rex_core/espeak-ng-data/lang/poz/mi
    - assets/rex_core/espeak-ng-data/lang/poz/ms
    - assets/rex_core/espeak-ng-data/lang/roa/an
    - assets/rex_core/espeak-ng-data/lang/roa/ca
    - assets/rex_core/espeak-ng-data/lang/roa/es
    - assets/rex_core/espeak-ng-data/lang/roa/es-419
    - assets/rex_core/espeak-ng-data/lang/roa/fr
    - assets/rex_core/espeak-ng-data/lang/roa/fr-BE
    - assets/rex_core/espeak-ng-data/lang/roa/fr-CH
    - assets/rex_core/espeak-ng-data/lang/roa/ht
    - assets/rex_core/espeak-ng-data/lang/roa/it
    - assets/rex_core/espeak-ng-data/lang/roa/pap
    - assets/rex_core/espeak-ng-data/lang/roa/pt
    - assets/rex_core/espeak-ng-data/lang/roa/pt-BR
    - assets/rex_core/espeak-ng-data/lang/roa/ro
    - assets/rex_core/espeak-ng-data/lang/sai/gn
    - assets/rex_core/espeak-ng-data/lang/sem/am
    - assets/rex_core/espeak-ng-data/lang/sem/ar
    - assets/rex_core/espeak-ng-data/lang/sem/he
    - assets/rex_core/espeak-ng-data/lang/sem/mt
    - assets/rex_core/espeak-ng-data/lang/sit/cmn
    - assets/rex_core/espeak-ng-data/lang/sit/cmn-Latn-pinyin
    - assets/rex_core/espeak-ng-data/lang/sit/hak
    - assets/rex_core/espeak-ng-data/lang/sit/my
    - assets/rex_core/espeak-ng-data/lang/sit/yue
    - assets/rex_core/espeak-ng-data/lang/sit/yue-Latn-jyutping
    - assets/rex_core/espeak-ng-data/lang/tai/shn
    - assets/rex_core/espeak-ng-data/lang/tai/th
    - assets/rex_core/espeak-ng-data/lang/trk/az
    - assets/rex_core/espeak-ng-data/lang/trk/ba
    - assets/rex_core/espeak-ng-data/lang/trk/cv
    - assets/rex_core/espeak-ng-data/lang/trk/kk
    - assets/rex_core/espeak-ng-data/lang/trk/ky
    - assets/rex_core/espeak-ng-data/lang/trk/nog
    - assets/rex_core/espeak-ng-data/lang/trk/tk
    - assets/rex_core/espeak-ng-data/lang/trk/tr
    - assets/rex_core/espeak-ng-data/lang/trk/tt
    - assets/rex_core/espeak-ng-data/lang/trk/ug
    - assets/rex_core/espeak-ng-data/lang/trk/uz
    - assets/rex_core/espeak-ng-data/lang/urj/et
    - assets/rex_core/espeak-ng-data/lang/urj/fi
    - assets/rex_core/espeak-ng-data/lang/urj/hu
    - assets/rex_core/espeak-ng-data/lang/urj/smj
    - assets/rex_core/espeak-ng-data/lang/zle/be
    - assets/rex_core/espeak-ng-data/lang/zle/ru
    - assets/rex_core/espeak-ng-data/lang/zle/ru-cl
    - assets/rex_core/espeak-ng-data/lang/zle/ru-LV
    - assets/rex_core/espeak-ng-data/lang/zle/uk
    - assets/rex_core/espeak-ng-data/lang/zls/bg
    - assets/rex_core/espeak-ng-data/lang/zls/bs
    - assets/rex_core/espeak-ng-data/lang/zls/hr
    - assets/rex_core/espeak-ng-data/lang/zls/mk
    - assets/rex_core/espeak-ng-data/lang/zls/sl
    - assets/rex_core/espeak-ng-data/lang/zls/sr
    - assets/rex_core/espeak-ng-data/lang/zlw/cs
    - assets/rex_core/espeak-ng-data/lang/zlw/pl
    - assets/rex_core/espeak-ng-data/lang/zlw/sk
    - assets/rex_core/espeak-ng-data/voices/!v/adam
    - assets/rex_core/espeak-ng-data/voices/!v/Alex
    - assets/rex_core/espeak-ng-data/voices/!v/Alicia
    - assets/rex_core/espeak-ng-data/voices/!v/Andrea
    - assets/rex_core/espeak-ng-data/voices/!v/Andy
    - assets/rex_core/espeak-ng-data/voices/!v/anika
    - assets/rex_core/espeak-ng-data/voices/!v/anikaRobot
    - assets/rex_core/espeak-ng-data/voices/!v/Annie
    - assets/rex_core/espeak-ng-data/voices/!v/announcer
    - assets/rex_core/espeak-ng-data/voices/!v/antonio
    - assets/rex_core/espeak-ng-data/voices/!v/AnxiousAndy
    - assets/rex_core/espeak-ng-data/voices/!v/aunty
    - assets/rex_core/espeak-ng-data/voices/!v/belinda
    - assets/rex_core/espeak-ng-data/voices/!v/benjamin
    - assets/rex_core/espeak-ng-data/voices/!v/boris
    - assets/rex_core/espeak-ng-data/voices/!v/caleb
    - assets/rex_core/espeak-ng-data/voices/!v/croak
    - assets/rex_core/espeak-ng-data/voices/!v/david
    - assets/rex_core/espeak-ng-data/voices/!v/Demonic
    - assets/rex_core/espeak-ng-data/voices/!v/Denis
    - assets/rex_core/espeak-ng-data/voices/!v/Diogo
    - assets/rex_core/espeak-ng-data/voices/!v/ed
    - assets/rex_core/espeak-ng-data/voices/!v/edward
    - assets/rex_core/espeak-ng-data/voices/!v/edward2
    - assets/rex_core/espeak-ng-data/voices/!v/f1
    - assets/rex_core/espeak-ng-data/voices/!v/f2
    - assets/rex_core/espeak-ng-data/voices/!v/f3
    - assets/rex_core/espeak-ng-data/voices/!v/f4
    - assets/rex_core/espeak-ng-data/voices/!v/f5
    - assets/rex_core/espeak-ng-data/voices/!v/fast
    - assets/rex_core/espeak-ng-data/voices/!v/Gene
    - assets/rex_core/espeak-ng-data/voices/!v/Gene2
    - assets/rex_core/espeak-ng-data/voices/!v/grandma
    - assets/rex_core/espeak-ng-data/voices/!v/grandpa
    - assets/rex_core/espeak-ng-data/voices/!v/gustave
    - assets/rex_core/espeak-ng-data/voices/!v/Henrique
    - assets/rex_core/espeak-ng-data/voices/!v/Hugo
    - assets/rex_core/espeak-ng-data/voices/!v/ian
    - assets/rex_core/espeak-ng-data/voices/!v/iven
    - assets/rex_core/espeak-ng-data/voices/!v/iven2
    - assets/rex_core/espeak-ng-data/voices/!v/iven3
    - assets/rex_core/espeak-ng-data/voices/!v/iven4
    - assets/rex_core/espeak-ng-data/voices/!v/Jacky
    - assets/rex_core/espeak-ng-data/voices/!v/john
    - assets/rex_core/espeak-ng-data/voices/!v/kaukovalta
    - assets/rex_core/espeak-ng-data/voices/!v/klatt
    - assets/rex_core/espeak-ng-data/voices/!v/klatt2
    - assets/rex_core/espeak-ng-data/voices/!v/klatt3
    - assets/rex_core/espeak-ng-data/voices/!v/klatt4
    - assets/rex_core/espeak-ng-data/voices/!v/klatt5
    - assets/rex_core/espeak-ng-data/voices/!v/klatt6
    - assets/rex_core/espeak-ng-data/voices/!v/Lee
    - assets/rex_core/espeak-ng-data/voices/!v/linda
    - assets/rex_core/espeak-ng-data/voices/!v/m1
    - assets/rex_core/espeak-ng-data/voices/!v/m2
    - assets/rex_core/espeak-ng-data/voices/!v/m3
    - assets/rex_core/espeak-ng-data/voices/!v/m4
    - assets/rex_core/espeak-ng-data/voices/!v/m5
    - assets/rex_core/espeak-ng-data/voices/!v/m6
    - assets/rex_core/espeak-ng-data/voices/!v/m7
    - assets/rex_core/espeak-ng-data/voices/!v/m8
    - assets/rex_core/espeak-ng-data/voices/!v/marcelo
    - assets/rex_core/espeak-ng-data/voices/!v/Marco
    - assets/rex_core/espeak-ng-data/voices/!v/Mario
    - assets/rex_core/espeak-ng-data/voices/!v/max
    - assets/rex_core/espeak-ng-data/voices/!v/Michael
    - assets/rex_core/espeak-ng-data/voices/!v/michel
    - assets/rex_core/espeak-ng-data/voices/!v/miguel
    - assets/rex_core/espeak-ng-data/voices/!v/Mike
    - assets/rex_core/espeak-ng-data/voices/!v/mike2
    - assets/rex_core/espeak-ng-data/voices/!v/Mr serious
    - assets/rex_core/espeak-ng-data/voices/!v/Nguyen
    - assets/rex_core/espeak-ng-data/voices/!v/norbert
    - assets/rex_core/espeak-ng-data/voices/!v/pablo
    - assets/rex_core/espeak-ng-data/voices/!v/paul
    - assets/rex_core/espeak-ng-data/voices/!v/pedro
    - assets/rex_core/espeak-ng-data/voices/!v/quincy
    - assets/rex_core/espeak-ng-data/voices/!v/Reed
    - assets/rex_core/espeak-ng-data/voices/!v/RicishayMax
    - assets/rex_core/espeak-ng-data/voices/!v/RicishayMax2
    - assets/rex_core/espeak-ng-data/voices/!v/RicishayMax3
    - assets/rex_core/espeak-ng-data/voices/!v/rob
    - assets/rex_core/espeak-ng-data/voices/!v/robert
    - assets/rex_core/espeak-ng-data/voices/!v/robosoft
    - assets/rex_core/espeak-ng-data/voices/!v/robosoft2
    - assets/rex_core/espeak-ng-data/voices/!v/robosoft3
    - assets/rex_core/espeak-ng-data/voices/!v/robosoft4
    - assets/rex_core/espeak-ng-data/voices/!v/robosoft5
    - assets/rex_core/espeak-ng-data/voices/!v/robosoft6
    - assets/rex_core/espeak-ng-data/voices/!v/robosoft7
    - assets/rex_core/espeak-ng-data/voices/!v/robosoft8
    - assets/rex_core/espeak-ng-data/voices/!v/sandro
    - assets/rex_core/espeak-ng-data/voices/!v/shelby
    - assets/rex_core/espeak-ng-data/voices/!v/steph
    - assets/rex_core/espeak-ng-data/voices/!v/steph2
    - assets/rex_core/espeak-ng-data/voices/!v/steph3
    - assets/rex_core/espeak-ng-data/voices/!v/Storm
    - assets/rex_core/espeak-ng-data/voices/!v/travis
    - assets/rex_core/espeak-ng-data/voices/!v/Tweaky
    - assets/rex_core/espeak-ng-data/voices/!v/UniRobot
    - assets/rex_core/espeak-ng-data/voices/!v/victor
    - assets/rex_core/espeak-ng-data/voices/!v/whisper
    - assets/rex_core/espeak-ng-data/voices/!v/whisperf
    - assets/rex_core/espeak-ng-data/voices/!v/zac
